---
title: "State of Oregon and Dual Language Immersion"
author: "Manuel Vazquez, Errol Kaylor, Tingyu Zou"
date: "2/25/2022"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme:
      version: 4
      bootswatch: minty
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE
                      )
#library(tmap)
library(edld652)
library(tidyverse)
library(skimr)
library(gghighlight)
library(arrow)
library(here)
library(rio)
library(ggrepel)
library(tigris)
library(leaflet)
library(flexdashboard)
library(rgdal)
```

```{r data setup, include=FALSE}

or_district_math_participation <- as_tibble(get_data("EDFacts_math_achievement_lea_2010_2019")) %>% 
  filter(STNAM == "OREGON")

or_district_math_achievement <- as_tibble(get_data("EDFacts_math_participation_lea_2013_2019")) %>% 
  filter(STNAM == "OREGON")

or_district_reading_participation <- as_tibble(get_data("EDFacts_rla_participation_lea_2013_2019")) %>% 
  filter(STNAM == "OREGON")

or_district_reading_achievement <- as_tibble(get_data("EDFacts_rla_achievement_lea_2010_2019")) %>% 
  filter(STNAM == "OREGON")

# or_district_ccd_fiscal_2012 <- as_tibble(get_data("NCES_CCD_fiscal_district_2012")) %>% 
#   filter(STNAM == "OREGON")

or_district_directory <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_directory")) %>%
  filter(STATENAME == "OREGON")

or_district_directory <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_directory")) %>% 
  filter(STATENAME == "OREGON")

or_district_el <- as_tibble(get_data("NCES_CCD_nonfiscal_district_2017_2021_english_learners")) %>% 
  filter(STATENAME == "OREGON") %>% 
  select(LEAID,
         SCHOOL_YEAR,
         LEP_COUNT)

or_district_membership <- as_tibble(read_parquet(here( "data", "district-membership-17-21.parquet"))) %>% 
  filter(STATENAME == "OREGON")

or_district_el_directory <- 
 left_join(or_district_directory,
           or_district_el,
           by="LEAID")

#Importing the file that has list of districts with dual language immersion schools in Oregon
dli <- import(here("data","districts_dli.xlsx")) %>%
  janitor::clean_names() %>%
  mutate(leaid = as.character(leaid))

# Filtering the EL file to only include years 2018-19
or_el <- or_district_el %>%
  filter(SCHOOL_YEAR == "2018-2019") %>%
  select(LEAID, LEP_COUNT) %>%
  janitor::clean_names()

# From the membership file, taking the number of White Students
or_enroll_white <- or_district_membership %>%
  filter(SCHOOL_YEAR == "2018-2019" & 
           GRADE == "No Category Codes" &
           RACE_ETHNICITY == "White") %>%
  group_by(LEAID) %>%
  summarize(student_white_count = sum(STUDENT_COUNT))

# creating the analytic file with necesarry variables, taking the overall enrollment
# which is represented by the "No category codes" value
or_enroll_total <- or_district_membership %>%
  filter(SCHOOL_YEAR == "2018-2019" & 
           GRADE == "No Category Codes" &
           RACE_ETHNICITY == "No Category Codes" & 
           SEX == "No Category Codes" &
         TOTAL_INDICATOR == "Education Unit Total" &
           STUDENT_COUNT > 0 &
           !is.na(STUDENT_COUNT) ) %>%
  left_join(or_enroll_white, by = "LEAID") %>%
  mutate(white_pct = (student_white_count/STUDENT_COUNT)*100,
         students_color_pct = 100 - white_pct) %>%
  janitor::clean_names() %>%
  left_join(dli,by="leaid") %>%
  left_join(or_el,by = "leaid") %>%
  select(leaid,lea_name,student_count,student_white_count,white_pct,schools_dli, lep_count, students_color_pct) %>%
  mutate(schools_dli = ifelse(is.na(schools_dli),0,schools_dli),
         el_pct = (lep_count/student_count)*100,
         dli_cat = case_when(schools_dli == 0 ~ "0 schools",
                             schools_dli > 0 & schools_dli < 3 ~"1-2 schools",
                             schools_dli > 2 & schools_dli < 6 ~ "3-5 schools",
                             schools_dli > 3 ~"More than 5 schools"
                             ))
  


s <- get_data("EDFacts_rla_achievement_lea_2010_2019")
ach <- filter(s,STNAM=="OREGON") %>% 
  drop_na(LEP_RLA00PCTPROF)

ach2 <- ach %>% 
  rename(leaid=LEAID)

FinalDF <- left_join(or_enroll_total,ach2,by="leaid") %>% 
  drop_na(LEP_RLA00PCTPROF)

#remove rows that are privacy protected
Final <- filter(FinalDF,LEP_RLA00PCTPROF!="PS",
                LEP_RLA00PCTPROF!="GE50",
                LEP_RLA00PCTPROF!="LT50",
                LEP_RLA00PCTPROF!="LE20")




Df <- Final %>%
  mutate(value1 = as.numeric(str_extract(LEP_RLA00PCTPROF, "\\d+")),
      value2 = abs(as.numeric(str_extract(LEP_RLA00PCTPROF, "\\-\\d+"))),
      LEP_prof_read = ifelse(is.na(value2),value1,((value1+value2)/2))) %>%
  select(leaid,lea_name, white_pct,schools_dli,lep_count,students_color_pct,el_pct,dli_cat,LEP_RLA00PCTPROF,value1,value2,LEP_prof_read) %>% 
  mutate(district_name = gsub("SD.*", "", lea_name)) %>% 
  mutate(Dli2=case_when(schools_dli == 0 ~ "absence of DLI programs", dli_cat != 0  ~ "presence of DLI programs"))

dli_read <- Df %>%
  group_by(dli_cat) %>%
  summarize(mean = mean(LEP_prof_read))


or_enroll_total_edit <- or_enroll_total %>%
mutate(LEAID = leaid)

full_dataset <- left_join(or_district_el_directory,
                           or_district_reading_achievement,
                           by="LEAID") %>%
                 left_join(or_district_reading_participation,
                           by="LEAID") %>%
                 left_join(or_enroll_total_edit,
                           by="LEAID")
or_district_data <- school_districts(state=41)

```


# Oregon District Data

Background {.sidebar data-width=350}
-----------------------------------------------------------------------

The state of Oregon is home to 50,500 students characterized as English Learners across its ~200 districts. These students represent **close to 9%** of reported students in Oregon schools, across all grades. 

Initial Versions of the graph chart EL populations compared to total student population of each district.

Our second visualization plots raw counts of students across Oregon, showing areas of greater density. These counts are not intuitive, and make more sense when displayed relative to the overall number of students. 

Understanding that the relative need for EL student support varies dramatically across Oregon allows for allocating resources to better serve as many students as possible, while acknowledging what more isolated EL students may face.



Column {.tabset}
-----------------------------------------------------------------------

### Chart B

```{r}

p1 <- full_dataset %>%
  ggplot(aes(student_count,fct_reorder(lea_name,student_count)))+
  geom_point(aes(size=lep_count))+
  theme_minimal()+
  labs(title = "EL Students are not equally distributed across School Districts in Oregon",
       x= "Number of Total Students")

p1
```

### EL Distribution V1

```{r}
pal <- colorNumeric(
 palette = "Blues",
 domain = full_dataset$LEP_COUNT)

first_map <- leaflet(or_district_data) %>%
 addProviderTiles("CartoDB.Positron") %>% 
 addPolygons(color = ~pal(full_dataset$LEP_COUNT),
             weight = 0.5,
             fillOpacity = 1) %>% 
  addLegend("bottomright", pal = pal, values = ~full_dataset$LEP_COUNT,
    title = "Distribution of LEP Students Across Oregon",
    opacity = 1)

first_map
```


# Set 2 Tingyu

Background {.sidebar data-width=350}
-----------------------------------------------------------------------

At first, there's not a clear idea if I would focus on the whole state of Oregon or specific subdistricts. Finally, We decide that we'd like a plot which can provide a whole map of the distribution of English learners and their achievement in reading all over the state of Oregon. The y-axis in this plot actually didn't answer our reshearch question well. Besides, the observations of the percentage of English learners scoring at or above proficiency are messy including both numbers and ranges. Obviously, it didn't work because it's neither informative nor neat.

This version looks better because it not only answers our research question well but also looks tidy. This plot displays the distribution of English learners as well as their achievement in reading across the state of Oregon. There is an uneven distribution of Dual language programs in Oregon. Meanwhile, we were curious if Dual language immersion programs make differences in the achievenment of English learners? To answer this question, three v-lines were added in the plot. The differences are explicit as shown in the v-lines, the mean of the percentage of English learners scoring at or above proficiency in Oregon state,subdistrics without Dual language programs and subdistricts with the presence of Dual language programs are 42, 41 and 44, respectively. 

Column {.tabset}
-----------------------------------------------------------------------
### First iteration of the graph: 


```{r}
Final %>% 
  ggplot(aes(el_pct, white_pct)) +
        geom_point(color = "gray70")+
        geom_text_repel(aes(label = LEP_RLA00PCTPROF))+
        theme_minimal() +
        labs(title = "Destrict and Achievement", 
             y = "Percent white", 
             x = "Percent EL of total enrollment") 
  
  
```

### Final iteration: 

```{r fig.width=12, fig.height = 15}
dli_read <- Df %>%
  group_by(Dli2) %>%
  summarize(mean = mean(LEP_prof_read))

Df %>% 
ggplot(aes(y=forcats::fct_reorder(district_name,LEP_prof_read),x=LEP_prof_read, color = dli_cat)) +
  geom_point(aes(size = el_pct), color = "grey80") +
  geom_point(data = filter(Df,schools_dli > 0 & !is.na(dli_cat)),
             aes(size = el_pct, 
                 color = as.factor(dli_cat)),
                alpha = .7) + 
  geom_vline(xintercept =42, alpha = .6) +
  geom_vline(xintercept =41, linetype = "dashed", color = "#cfcfcf", alpha = .6, size = 1.25) +
  geom_vline(xintercept =44, linetype = "dashed",  color = "#808080", alpha = .6, size = 1.25) +
  geom_text(aes(x=41, label="no DLI", y=80), colour="#cfcfcf", angle=90,vjust = -0.75, text=element_text(size=11)) +
  geom_text(aes(x=44, label="DLI", y=80), colour="#808080", angle=90,vjust = 1.75, text=element_text(size=11))+
  xlim(25,75) +
  theme_minimal() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        axis.text.y = element_text(size = 4 ),
        axis.text.x = element_text(size = 6)) +
  labs(title = "Distribution of English learners that scored at or above proficient in Oregon",
              y = "", 
              x = "Percentage of English learners that scored at or above proficient",
              color = "Dual language immersion programs",
              size="Percent EL of total enrollment")+
  theme(legend.title = element_text(size = 8))
```



# DLI in Oregon

Background {.sidebar data-width=350}
-----------------------------------------------------------------------
**Research Area: Examining concentration of dual language immersion programs in Oregon.**  Dual language immersion programs aim to promote high academic achievement, full biliteracy, and develop social consciousness by grouping EL and monolingual students into one classroom while splitting instruction in English and a partner language. Evidence from rigorous studies finds that TWDLI programs has a positive impact on the academic achievement of EL classified students (Steele, et al., 2017) and meta-analysis that examine the effects of bilingual education also finds a positive relationship (Rolstad et. al., 2018). 

When I started this work, my intention was to examine if there are any patterns in the concentration of district with DLI programs by linguistic and racial diversity. More specifically, I wanted to know if districts with high EL and racial diversity were benefiting from these programs. My first graph plotted concentration of EL against pct white in the y-axis. Knowing that some districts might have low EL rates but a lot of EL students, I also included the raw number of students in the graph by tying size of points to raw count of EL students. 

I was also thinking of dividing districts into quadrants and having four typologies of districts. However, I had to drop that concept because there weren't really four types of districts, the relationship between x and y variables were fairly linear.

I ended up with **two final graphs** that incorporated many improvements relative to the first iteration of the graph. First, I changed the colors and adjusted the sizing scale so that they are more prominent and we can see differences. I also used ggrepel to highlight specific districts. Additionally, I changed the y-axis to center the message more on linguistically/racially diverse students and remove focus from white students. Lastly, I added a descriptive title that provided a key takeaway. 

The **first final graph** highlighted where the DLI districts are located and emphasizes that racially & linguistically diverse districts have the largest programs. For example, Portland, Beaverton, Hillsboro, Salem-Keizer, and Woodburn all have large DLI programs and serve a high proportion of EL students.

**The second graph** kept many of these changes but communicated an additional finding which is that **there are at least seven districts in Oregon that serve a high number of EL students but don't offer DLI programs.** These districts serve more than 500 current EL students and have high linguistic and racial diversity. Research indicates that many of these students could benefit from programs such as DLI. 



Column {.tabset}
-----------------------------------------------------------------------

### First Iteration of the graph

```{r fig.width=15, fig.height = 12}
## Creating a plot that visualizes DLI concentration by white and EL concentration in Oregon
or_enroll_total%>%
  ggplot(aes(x = el_pct, y=white_pct)) +
  geom_point(aes(size = lep_count), color = "grey80") +
  geom_point(data = filter(or_enroll_total,schools_dli > 0 & !is.na(dli_cat)),
             aes(el_pct,y = white_pct, size = lep_count, color = as.factor(dli_cat))) +
  scale_size_continuous(
    name = "Number of EL students",
    breaks = c(50,100,500,750, 1000)) +
  xlim(0,35) +
# create the quadrants
  geom_segment(aes(x = 35, y = 0, xend = 35, yend = 100)) +
  geom_segment(aes(x = 0, y = 0, xend = 0, yend = 100)) +
  geom_segment(aes(x = 0, y = 0, xend = 35, yend = 0)) +
  geom_segment(aes(x = 0, y = 60, xend = 35, yend = 60)) +
  geom_segment(aes(x = 10, y = 0, xend = 10, yend = 100)) +
  geom_segment(aes(x = 0, y = 100, xend = 35, yend = 100)) +
  # quadrant labels
  annotate("text", x = 5, y = 95, alpha = 0.35, label = "High White, Low EL Districts") +
  annotate("text", x = 20, y = 95, alpha = 0.35, label = " ") +
  annotate("text", x = 20, y = 15, alpha = 0.35, label = "Low White, High EL Districts\n\ (Candiates for DLI programs)") +
  annotate("text", x = 5, y = 15, alpha = 0.35, label = " ") +
  theme_minimal() +
  labs(
       y = "Percent white", 
       x = "Percent EL of total enrollment")
  


```

### Final Iteration - Graph 1 

```{r fig.width=15, fig.height = 12}
or_enroll_total%>%
  ggplot(aes(x = el_pct, y=students_color_pct)) +
# create the quadrants
  geom_segment(aes(x = 35, y = 0, xend = 35, yend = 100), color = "grey90") +
  geom_segment(aes(x = 0, y = 0, xend = 0, yend = 100), color = "grey90") +
  geom_segment(aes(x = 0, y = 0, xend = 35, yend = 0), color = "grey90") +
  geom_segment(aes(x = 0, y = 40, xend = 35, yend = 40), color = "grey90") +
  geom_segment(aes(x = 10, y = 0, xend = 10, yend = 100), color = "grey90") +
  geom_segment(aes(x = 0, y = 100, xend = 35, yend = 100),color = "grey90") +
  # quadrant labels
  annotate("text", x = 20, y = 95, alpha = 0.35, label = "Racially & Linguistically \n\ diverse districts") +
    geom_point(aes(size = lep_count), color = "grey70") +
  geom_point(data = filter(or_enroll_total,schools_dli > 0 & !is.na(dli_cat)),
             aes(el_pct,y = students_color_pct, 
                 size = lep_count, 
                 color = as.factor(dli_cat)),
             alpha = .7)+
  geom_text_repel(data = filter(or_enroll_total, lep_count > 750 & schools_dli > 5),
                  aes(label = lea_name), min.segment.length = 0, box.padding = 1.05) +
  scale_size_continuous(
    name = "Number of EL students",
    breaks = c(100,500, 1000, 2000, 4000, 6000),
    range = c(1,10)) +
  colorblindr::scale_color_OkabeIto(
    name = "Number of DLI schools"
  ) +
  xlim(0,35) +
  annotate("text", x = 5, y = 100, alpha = 0.35, label = " ") +
  theme_minimal() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "right",
        legend.box = "vertical") +
  labs(title = "Districts with High concentration of EL students have larger DLI programs",
       subtitle = "Yet, there is a high concentration of DLI programs in low diversity districts",
       y = "Percent students of color", 
       x = "Percent EL",
       caption = " \n\ Note: DLI = Dual language immersion") 
```

### Final Iteration - Graph 2

```{r fig.width=15, fig.height = 12}
or_enroll_total%>%
  ggplot(aes(x = el_pct, y=students_color_pct)) +
  # create the quadrants
  geom_segment(aes(x = 35, y = 0, xend = 35, yend = 100),color = "grey90") +
  geom_segment(aes(x = 0, y = 0, xend = 0, yend = 100),color = "grey90") +
  geom_segment(aes(x = 0, y = 0, xend = 35, yend = 0),color = "grey90") +
  geom_segment(aes(x = 0, y = 40, xend = 35, yend = 40),color = "grey90") +
  geom_segment(aes(x = 10, y = 0, xend = 10, yend = 100),color = "grey90") +
  geom_segment(aes(x = 0, y = 100, xend = 35, yend = 100),color = "grey90") +
  # quadrant labels
  annotate("text", x = 20, y = 95, alpha = 0.35, label = "Linguistically diverse districts \n\ (Candidates for DLI programs)") +
  geom_point(aes(size = lep_count), color = "grey70") +
  geom_point(data = filter(or_enroll_total,schools_dli < 1 & !is.na(dli_cat) & lep_count >500),
             aes(el_pct,y = students_color_pct, 
                 size = lep_count),
             color = "aquamarine3",
             alpha = .7)+
  # geom_point(data = filter(or_enroll_total,schools_dli > 0 & !is.na(dli_cat)),
  #            aes(el_pct,y = students_color_pct, 
  #                size = lep_count, 
  #                color = as.factor(dli_cat)),
  #            alpha = .7)+
  geom_text_repel(data = filter(or_enroll_total, lep_count > 500 & schools_dli == 0),
                  aes(label = lea_name), min.segment.length = 0, box.padding = 1.05) +
  scale_size_continuous(
    name = "Number of EL students",
    breaks = c(100,500, 1000, 2000, 4000, 6000),
    range = c(1,10)) +
  colorblindr::scale_color_OkabeIto(
    name = "Number of DLI schools"
  ) +
  xlim(0,35) +
  theme_minimal() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  labs(title = "In the 2018-19 school year, at least seven Oregon school districts served\n\ more than 500 EL students and did not offer DLI",
       subtitle = "",
       y = "Percent students of color", 
       x = "Percent EL ",
       caption = " \n\ Note: DLI = Dual language immersion. Each circle represents a district") 
```

